# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 919b15d950a179363df749665aa4ad000add887e448e6bd098db1f73cd9f7c0f7714b60525dc1c0394185820c010d9c47bf89d37c032d8ac9d3dee5659a7193d

test:
  secret_key_base: f5a88d96d810fceed433e5289fb2ba994ac327d8ae9ebdf1514810d17f66250798f76ee36d5293d6f7fd6d31a5b3fcb60e5c4bac2fabd68a31e66af8b806e9f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
